const hints = [
  "Você pode apertar F11 pra tela cheia.",
  "Mantenha seu navegador atualizado.",
  "Beba água.",
  "Esse site roda melhor sem 37 abas abertas.",
  "Pense antes de responder.",
  "Alguém realmente lê isso?",
  "Não alimente os pombos.",
  "Essa tela é totalmente desnecessaria",
  "Se estiver lendo isso, você já perdeu 3 segundos da sua vida.",
  "Reporte os bugs que achar, o dev agradece",
  "Você conhece o mario?",
  "Sabe por que não existe flor preta?",
  "Enquanto carrega, pense em todas as decisões erradas que te trouxeram até aqui.",
  "Se vc apertar na tela 100 vezes, nada acontece.",
  "Ler isso não emprega em nada na gameplay, então por que continuar?",
  "Esse jogo foi feito por alguem que não sabe diferenciar os porquês.",
  "Antigamente o R+ recebeu o nome de 'Escrita Esperta'... Ainda bem que mudamos de ideia",
  "The book is on the table",
  "Sabe por que a galinha atravessou a rua? não? serio?",
  "Aviso: Avisamos que por falta de aviso não avisaremos o aviso que era para avisar, portanto fiquem avisados deste aviso que avisamos. Qualquer duvida, avise!",
  "Não fique esperando o momento perfeito pra falar o que sente, porque ele pode simplesmente nunca acontecer.",
  "Não esqueça de fazer um alongamento.",
  "Essa dica está sendo exibida só pra te distrair.",
  "Loading... (podia ser mais rápido, né?)",
  "Você já pensou em aprender algo novo?",
  "Você sabia que o primeiro videogame foi criado em 1958?",
  "As batalhas diárias não se tornam mais fáceis, você se torna mais forte.",
  "Não leia isso tudo, aproveite o tempo para pensar no futuro... ah, você ja leu..",
  "Se estiver demorando mais de 15 minutos.. Tem algo muito errado com seu dispositivo.",
  "Amanhã é sempre depois de hoje.",
  "Se você permanecer nessa tela por 10 minutos algo acontecerá... quer descobrir?",
  "Digite 'DevModeArt()' no console do desenvolvedor (F12) para ativar todas as 'trapaças' e logs do jogo, além de pausar o tempo. Use com moderação.",
  "Experimente o R+ Literatura qualquer hora",
  "Dizem as lendas que o dev de R+ trabalhou por seis dias e descansou no sétimo... e no oitavo, no nono, no décimo... e segue firme nessa tradição até hoje.",
];
