const hints = [
  "Você pode apertar F11 pra tela cheia.",
  "Mantenha seu navegador atualizado.",
  "Beba água.",
  "Esse site roda melhor sem 37 abas abertas.",
  "O botão de fechar não é pra clicar por acidente.",
  "Pense antes de responder.",
  "Alguém realmente lê isso?",
  "Jogue acordado.",
  "Não alimente os pombos.",
  "A barra de rolagem não existe... ou pelo menos não devia existir.",
  "Isso aqui é só a tela de carregamento, relaxa.",
  "Essa tela é desnecessaria",
  "Essa tela so existe pela preguiça do desenvolvedor de otimizar o site",
  "Se estiver lendo isso, você já perdeu 3 segundos da sua vida.",
  "Reporte os bugs que achar, o dev agradece",
  "Se der erro, finge que é feature.",
  "Essa tela carrega por no maximo 4 segundos",
  "Essa dica foi patrocinada por ninguém.",
  "Você conhece o mario?",
  "Sim, tem alguém te observando... provavelmente seu reflexo.",
  "Não clique em lugares suspeitos. Tipo aquele X vermelho.",
  "Essa é só mais uma linha de texto aleatório. E daí?",
  "Já tentou desligar e ligar de novo? Até seu cérebro.",
  "Imagina um jogo que so carrega para sempre kkkkk... Eu não faria isso.. ou faria?",
  "Aceite o caos. O caos aceita você.",
  "Enquanto carrega, pense em todas as decisões erradas que te trouxeram até aqui.",
  "Se vc apertar na tela 10 vezes, o loading é pulado. JK",
  "Ler isso não emprega em nada na gameplay, então por que continuar?",
  "Sim, esse jogo foi feito por alguem que não sabe diferenciar os porquês, desculpa",
  "Você é especial! Se valorize <3",
  "O que você ta esperando?",
  "Curiosidade: antigamente o R+ recebeu o nome de 'Escrita Esperta'... Ainda bem que mudamos de ideia",
  "Esse site é feito com Tailwind Css e java script... como isso pode ser util para você? não sei",
  "As vezes algumas coisas não demonstram que são clicaveis..",
  "Se você quiser parar de ver essas dicas, tente desativar nas configurações... Vou sentir saudades :/",
  "/gamemode Creative",
  "Esse não tem salvamente em nuvem... se achar ruim, me pague um servidor",
  "Eu não estou sendo pago para escrever essas dicas... isso nem sequer são dicas na verdade",
  "Esse jogo não contem dragões... ainda",
  "Esse jogo não saiu oficialmente... ou saiu?",
  "The book is on the table",
  "Sabe por que a galinha atravessou a rua? não? serio?",
  "Aviso: Avisamos que por falta de aviso não avisaremos o aviso que era para avisar, portanto fiquem avisados deste aviso que avisamos. Qualquer duvida, avise!",
  "Sabia que o ato de pousar na lua recebe o nome de 'alunissagem'? Isso não tem nada a ver com o R+",
  "Lembra do 'o jogo'?",
  "Esse jogo é totalmente open-source... você não sabe o que significa? bom... não é importante",
  "Não fique esperando o momento perfeito pra falar o que sente, porque ele pode simplesmente nunca acontecer.",
  "Não esqueça de fazer um alongamento.",
  "Essa dica está sendo exibida só pra te distrair.",
  "Loading... (podia ser mais rápido, né?)",
  "A paciência é uma virtude...",
  "Você já pensou em aprender a programar? (p.s. Não recomendo)",
  "Você sabia que o primeiro videogame foi criado em 1958?",
  "As batalhas diárias não se tornam mais fáceis, você se torna mais forte",
  "Agua é um dos recursos mais escassos do universo, não desperdice",
];
